# Generated by Django 4.1.7 on 2023-03-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_rating', models.FloatField()),
                ('number_of_ratings', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('movieId', models.IntegerField()),
                ('War', models.IntegerField()),
                ('Fantasy', models.IntegerField()),
                ('Adventure', models.IntegerField()),
                ('Horror', models.IntegerField()),
                ('Documentary', models.IntegerField()),
                ('Mystery', models.IntegerField()),
                ('Drama', models.IntegerField()),
                ('Children', models.IntegerField()),
                ('Romance', models.IntegerField()),
                ('IMAX', models.IntegerField()),
                ('Comedy', models.IntegerField()),
                ('Western', models.IntegerField()),
                ('Animation', models.IntegerField()),
                ('No_genre', models.IntegerField()),
                ('Crime', models.IntegerField()),
                ('Musical', models.IntegerField()),
                ('Thriller', models.IntegerField()),
                ('Sci_Fi', models.IntegerField()),
                ('Action', models.IntegerField()),
                ('Film_Noir', models.IntegerField()),
            ],
        ),
    ]
