# Generated by Django 4.1.7 on 2023-03-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
