# Generated by Django 4.1.7 on 2023-03-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0009_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Action',
            field=models.IntegerField(null=True),
        ),
    ]
