# Generated by Django 4.1.7 on 2023-03-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0010_alter_movie_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='Suggestion',
        ),
    ]
