# Generated by Django 4.1.7 on 2023-03-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0011_rename_suggestions_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion_2',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='suggestion_3',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_11',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_13',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_14',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_15',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_9',
            field=models.IntegerField(),
        ),
    ]
