# Generated by Django 4.1.7 on 2023-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0012_remove_suggestion_suggestion_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_3',
            field=models.IntegerField(default=0),
        ),
    ]
