# Generated by Django 4.1.7 on 2023-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0013_suggestion_suggestion_2_suggestion_suggestion_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_3',
            field=models.IntegerField(default=-1),
        ),
    ]
