# Generated by Django 4.1.7 on 2023-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0015_suggestion_suggestion_16_suggestion_suggestion_17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_35',
            field=models.IntegerField(default=-1),
        ),
    ]
