# Generated by Django 4.1.7 on 2023-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborative', '0017_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movieId',
            field=models.IntegerField(),
        ),
    ]
